import re

file_path = "c:/Users/User/portfolioDevDorth/backend/alembic/versions/82db131e0a29_add_stats_and_dbfile.py"

with open(file_path, "r") as f:
    content = f.read()

# Add inspector import
if "from sqlalchemy.engine.reflection import Inspector" not in content:
    content = content.replace("import sqlalchemy as sa", "import sqlalchemy as sa\nfrom sqlalchemy.engine.reflection import Inspector")

# Find the start of upgrade()
upgrade_start_match = re.search(r"def upgrade\(\) -> None:\s+\"\"\"Upgrade schema\.\"\"\"\s+# ### commands auto generated by Alembic - please adjust! ###", content)

if upgrade_start_match:
    setup_code = """
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
"""
    content = content[:upgrade_start_match.end()] + setup_code + content[upgrade_start_match.end():]

# Now for each op.create_table, wrap it
tables_to_wrap = ['certifications', 'experiences', 'files', 'profiles', 'projects', 'skills', 'users']

for table in tables_to_wrap:
    # Find op.create_table(table, ... op.create_index(...)
    # The regex needs to capture the specific block.
    # It's easier to replace op.create_table('table', with if 'table' not in tables:\n        op.create_table('table',
    # and indent the rest properly, but that's hard with regex. 
    pass

# Actually, the simplest way is to just do a try/except ProgrammingError for the entire block? No, PostgreSQL will abort the transaction on the first error. 
# Another simple way is:
# op.execute("CREATE TABLE IF NOT EXISTS certifications (...)") but alembic has `op.create_table`.

# Let's just do a big replace since the file isn't huge.
# We will just write the Python script to write a targeted new script.
