"""Add resume dynamic fields

Revision ID: 39341568f506
Revises: c5d6e7f8g9h0
Create Date: 2026-04-10 20:02:01.190668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39341568f506'
down_revision: Union[str, Sequence[str], None] = 'c5d6e7f8g9h0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns that might be missing in Postgres
    try:
        op.add_column('profiles', sa.Column('about_image_url', sa.String(), nullable=True))
    except Exception:
        pass
        
    try:
        op.add_column('profiles', sa.Column('resume_languages', sa.JSON(), nullable=True))
    except Exception:
        pass
        
    try:
        op.add_column('profiles', sa.Column('resume_education', sa.JSON(), nullable=True))
    except Exception:
        pass
        
    try:
        op.add_column('profiles', sa.Column('resume_website', sa.String(), nullable=True))
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'resume_website',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'resume_education',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'resume_languages',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('profiles', 'about_image_url')
    op.alter_column('certifications', 'file_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('certifications', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
